name: My CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirement.txt

      - name: Run Black (Code Formatter Check)
        run: black --check .

      - name: Run Flake8 (Line Check)
        run: flake8 .

      - name: Run tests with coverage
        run: |
           coverage run -m pytest tests/
           coverage report -m
           coverage html

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with: 
          name: coverage-report
          path: htmlcov

      - name: Train and save ML model
        run: python train_model.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.joblib
